[versions]
# plugins
androidGradle                       = "7.4.0"
detekt                              = "1.22.0-RC1"
detektTwitterCompose                = "0.0.26"
junit                               = "1.8.2.1"
ksp                                 = "1.7.20-1.0.6"
ktLint                              = "3.12.0"

# production libraries
coil                                = "2.2.2"
compose                             = "1.3.3"
composeMaterial                     = "1.3.1"
composeMaterial3                    = "1.0.1"
composeAccompanist                  = "0.29.0-alpha"
composeCompiler                     = "1.3.2"
composeNavigation                   = "2.5.2"
composeNavigationHilt               = "1.0.0"
desugar                             = "2.0.0"
hilt                                = "2.44.2"
kotlin                              = "1.7.20"
kotlinCoroutines                    = "1.6.4"
kotlinSerialization                 = "1.4.1"
kotlinSerializationConverter        = "0.8.0"
lifecycle                           = "2.5.1"
material                            = "1.7.0"
okHttpLoggingInterceptor            = "5.0.0-alpha.11"
retrofit                            = "2.9.0"
room                                = "2.5.0"
timber                              = "5.0.1"

# test libraries
testJunit                           = "5.9.1"
testMockk                           = "1.13.2"
testTurbine                         = "0.11.0"

# android test libraries
testAndroidCore                     = "1.5.0" # fix crash on Android 13 - https://developer.android.com/jetpack/androidx/releases/test#core_150_2
testAndroidRunner                   = "1.5.2"


[plugins]
androidApplication                  = { id = "com.android.application", version.ref = "androidGradle" }
androidLibrary                      = { id = "com.android.library", version.ref = "androidGradle" }
detekt                              = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt                                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit                               = { id = "de.mannodermaus.android-junit5", version.ref = "junit" }
kotlin                              = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt                          = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinParcelize                     = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization                 = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktLint                              = { id = "org.jmailen.kotlinter", version.ref = "ktLint" }


[libraries]
# production libraries
coil                                = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coilVideo                           = { module = "io.coil-kt:coil-video", version.ref = "coil" }
coilGif                             = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
composeAccompanistSwipeRefresh      = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "composeAccompanist" }
composeAccompanistPermission        = { module = "com.google.accompanist:accompanist-permissions", version.ref ="composeAccompanist" }
composeAccompanistPager             = { module = "com.google.accompanist:accompanist-pager", version.ref ="composeAccompanist" }
composeAccompanistPagerIndicator    = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref ="composeAccompanist" }
composeMaterial3                    = { module = "androidx.compose.material3:material3", version.ref ="composeMaterial3" }
composeMaterial                     = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
composeNavigation                   = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
composeNavigationHilt               = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "composeNavigationHilt" }
desugar                             = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
detektTwitterCompose                = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterCompose" }
hilt                                = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler                        = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlinCoroutines                    = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinSerialization                 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinSerializationConverter        = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinSerializationConverter" }
lifecycleViewModel                  = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material                            = { module = "com.google.android.material:material", version.ref = "material" }
okHttpLoggingInterceptor            = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttpLoggingInterceptor" }
retrofit                            = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room                                = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler                        = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx                             = { module = "androidx.room:room-ktx", version.ref = "room" }
timber                              = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# test libraries
testJunit                           = { module = "org.junit.jupiter:junit-jupiter", version.ref = "testJunit" }
testKotlin                          = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
testKotlinCoroutines                = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
testMockk                           = { module = "io.mockk:mockk", version.ref = "testMockk" }
testTurbine                         = { module = "app.cash.turbine:turbine", version.ref = "testTurbine" }

# android test libraries
testAndroidCompose                  = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
testAndroidCore                     = { module = "androidx.test:core-ktx", version.ref = "testAndroidCore" }
testAndroidHilt                     = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
testAndroidHiltCompiler             = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
testAndroidRunner                   = { module = "androidx.test:runner", version.ref = "testAndroidRunner" }

# debug libraries
debugComposeManifest                = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }


[bundles]
common = [
    "composeMaterial",
    "composeNavigation",
    "hilt",
    "kotlinCoroutines",
    "timber"
]

commonTest = [
    "testJunit",
    "testKotlin",
    "testKotlinCoroutines",
    "testMockk",
    "testTurbine"
]
